POST http://localhost:3333/auth/register
Content-Type: application/json

{
  "email": "tes2t@example.com",
  "username": "Bob123",
  "password": "verysecurepassword123"
}

###

POST http://localhost:3333/auth/login
Content-Type: application/json

{
  "username": "tes2t@example.com",
  "password": "verysecurepassword123"
}

###

GET http://localhost:3333/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJvYjEyMyIsInN1YiI6IjA1YjI0MTIyLWIwNjItNDU5OC05NWY5LTk3MGUxZjAyZDczMCIsImlhdCI6MTY0MTkzMzUwMSwiZXhwIjoxNjQxOTQwNzAxfQ.Iym6CmRPiD-es_YDYh89gEF7Y3hFToM9uyffNUY1LGE
